


/* Automatically generated by glib-mkenums */

#include "dacp-share.h"
#include "dacp-player.h"
#include "dmap-mdns-publisher.h"
#include "dmap-mdns-browser.h"
#include "dmap-connection.h"
#include "dmap-enums.h"

/* enumerations from "./dacp-player.h" */
GType
dacp_repeat_state_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DACP_REPEAT_NONE, "DACP_REPEAT_NONE", "none" },
      { DACP_REPEAT_SINGLE, "DACP_REPEAT_SINGLE", "single" },
      { DACP_REPEAT_ALL, "DACP_REPEAT_ALL", "all" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DACPRepeatState", values);
  }
  return etype;
}
GType
dacp_play_state_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DACP_PLAY_STOPPED, "DACP_PLAY_STOPPED", "stopped" },
      { DACP_PLAY_PAUSED, "DACP_PLAY_PAUSED", "paused" },
      { DACP_PLAY_PLAYING, "DACP_PLAY_PLAYING", "playing" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DACPPlayState", values);
  }
  return etype;
}

/* enumerations from "./dmap-connection.h" */
GType
dmap_connection_state_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_GET_INFO, "DMAP_GET_INFO", "get-info" },
      { DMAP_LOGIN, "DMAP_LOGIN", "login" },
      { DMAP_GET_REVISION_NUMBER, "DMAP_GET_REVISION_NUMBER", "get-revision-number" },
      { DMAP_GET_DB_INFO, "DMAP_GET_DB_INFO", "get-db-info" },
      { DMAP_GET_SONGS, "DMAP_GET_SONGS", "get-songs" },
      { DMAP_GET_PLAYLISTS, "DMAP_GET_PLAYLISTS", "get-playlists" },
      { DMAP_GET_PLAYLIST_ENTRIES, "DMAP_GET_PLAYLIST_ENTRIES", "get-playlist-entries" },
      { DMAP_LOGOUT, "DMAP_LOGOUT", "logout" },
      { DMAP_DONE, "DMAP_DONE", "done" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPConnectionState", values);
  }
  return etype;
}

/* enumerations from "./dmap-mdns-browser.h" */
GType
dmap_mdns_browser_service_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_MDNS_BROWSER_SERVICE_TYPE_INVALID, "DMAP_MDNS_BROWSER_SERVICE_TYPE_INVALID", "invalid" },
      { DMAP_MDNS_BROWSER_SERVICE_TYPE_DAAP, "DMAP_MDNS_BROWSER_SERVICE_TYPE_DAAP", "daap" },
      { DMAP_MDNS_BROWSER_SERVICE_TYPE_DPAP, "DMAP_MDNS_BROWSER_SERVICE_TYPE_DPAP", "dpap" },
      { DMAP_MDNS_BROWSER_SERVICE_TYPE_DACP, "DMAP_MDNS_BROWSER_SERVICE_TYPE_DACP", "dacp" },
      { DMAP_MDNS_BROWSER_SERVICE_TYPE_RAOP, "DMAP_MDNS_BROWSER_SERVICE_TYPE_RAOP", "raop" },
      { DMAP_MDNS_BROWSER_SERVICE_TYPE_LAST, "DMAP_MDNS_BROWSER_SERVICE_TYPE_LAST", "last" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPMdnsBrowserServiceType", values);
  }
  return etype;
}
GType
dmap_mdns_browser_transport_protocol_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL_TCP, "DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL_TCP", "tcp" },
      { DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL_UDP, "DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL_UDP", "udp" },
      { DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL_LAST, "DMAP_MDNS_BROWSER_TRANSPORT_PROTOCOL_LAST", "last" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPMdnsBrowserTransportProtocol", values);
  }
  return etype;
}
GType
dmap_mdns_browser_error_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_MDNS_BROWSER_ERROR_NOT_RUNNING, "DMAP_MDNS_BROWSER_ERROR_NOT_RUNNING", "not-running" },
      { DMAP_MDNS_BROWSER_ERROR_FAILED, "DMAP_MDNS_BROWSER_ERROR_FAILED", "failed" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPMdnsBrowserError", values);
  }
  return etype;
}

/* enumerations from "./dmap-mdns-publisher.h" */
GType
dmap_mdns_publisher_error_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_MDNS_PUBLISHER_ERROR_NOT_RUNNING, "DMAP_MDNS_PUBLISHER_ERROR_NOT_RUNNING", "not-running" },
      { DMAP_MDNS_PUBLISHER_ERROR_FAILED, "DMAP_MDNS_PUBLISHER_ERROR_FAILED", "failed" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPMdnsPublisherError", values);
  }
  return etype;
}

/* enumerations from "./dmap-record.h" */
GType
dmap_media_kind_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_MEDIA_KIND_MUSIC, "DMAP_MEDIA_KIND_MUSIC", "music" },
      { DMAP_MEDIA_KIND_MOVIE, "DMAP_MEDIA_KIND_MOVIE", "movie" },
      { DMAP_MEDIA_KIND_PODCAST, "DMAP_MEDIA_KIND_PODCAST", "podcast" },
      { DMAP_MEDIA_KIND_TV_SHOW, "DMAP_MEDIA_KIND_TV_SHOW", "tv-show" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPMediaKind", values);
  }
  return etype;
}

/* enumerations from "./dmap-structure.h" */
GType
dmap_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { DMAP_TYPE_BYTE, "DMAP_TYPE_BYTE", "byte" },
      { DMAP_TYPE_SIGNED_INT, "DMAP_TYPE_SIGNED_INT", "signed-int" },
      { DMAP_TYPE_SHORT, "DMAP_TYPE_SHORT", "short" },
      { DMAP_TYPE_INT, "DMAP_TYPE_INT", "int" },
      { DMAP_TYPE_INT64, "DMAP_TYPE_INT64", "int64" },
      { DMAP_TYPE_STRING, "DMAP_TYPE_STRING", "string" },
      { DMAP_TYPE_DATE, "DMAP_TYPE_DATE", "date" },
      { DMAP_TYPE_VERSION, "DMAP_TYPE_VERSION", "version" },
      { DMAP_TYPE_CONTAINER, "DMAP_TYPE_CONTAINER", "container" },
      { DMAP_TYPE_POINTER, "DMAP_TYPE_POINTER", "pointer" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("DMAPType", values);
  }
  return etype;
}



